<a href="https://colab.research.google.com/github/SBekzod/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# building > room > person
# import numpy as np
from numpy import ones

arr = ones((4, 2, 3))

print("arr:\n", arr, "\n")

print("dimension:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)

arr:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] 

dimension: 3
shape: (4, 2, 3)
size: 24


In [ ]:
# dtype()
import numpy as np
arr1 = np.array([1, 2, 3])
print("arr1.item:", arr1.itemsize)
print("arr1.dtype >", arr1.dtype, arr1.nbytes, "\n")

arr2 = np.array([1, 2, 3], dtype='int32')
print("arr2.item:", arr2.itemsize)
print("arr2.dtype >", arr2.dtype, arr2.nbytes, "\n")

arr3 = np.ones((1000))
print(arr3.nbytes)
arr4 = np.ones((1000), dtype='int32')
print(arr4.nbytes)


arr1.item: 8
arr1.dtype > int64 24 

arr2.item: 4
arr2.dtype > int32 12 

8000
4000


In [ ]:
# reshape()
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = arr1.reshape(2, 3)

print("arr2:", arr2)

arr2: [[1 2 3]
 [4 5 6]]


In [ ]:
# ndim
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.ndim)

1


In [ ]:
# arange
arr = np.arange(1, 5)
print(arr)

[1 2 3 4]


In [ ]:
# sum() mean() max() min()
arr = np.array([12, 2, 3, 7, 5, 7])

print("sum:", arr.sum())
print("mean:", arr.mean())
print("max:", arr.max())
print("min:", arr.min())

sum: 36
mean: 6.0
max: 12
min: 2


In [ ]:
# flatten()

arr = np.array([[12, 2, 3], [1, 2, 5]])
print("flatten:", arr.flatten())

flatten: [12  2  3  1  2  5]


In [ ]:
# T - transpose
arr1 = np.array([[12, 2, 3, 4], [1, 2, 5, 8]])
print("arr1.transpose:\n", arr1.T, "\n")

arr2 = np.array([
    [[12, 2, 3, 4], [1, 2, 5, 8]],
    [[17, 5, 2, 4], [8, 7, 5, 3]],
    [[7, 15, 0, 2], [3, 1, 9, 1]],
  ])
print("arr2.transpose:\n", arr2.transpose(1,0,2))

arr1.transpose:
 [[12  1]
 [ 2  2]
 [ 3  5]
 [ 4  8]] 

arr2.transpose:
 [[[12  2  3  4]
  [17  5  2  4]
  [ 7 15  0  2]]

 [[ 1  2  5  8]
  [ 8  7  5  3]
  [ 3  1  9  1]]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 0], [5, 7]])

# haqiqiy linier kopaytirish (zamonaviy)
multip1 = arr1 @ arr2
print("multip1:", multip1, "\n")

# dot function
multip2 = np.dot(arr1, arr2)
print("multip2:", multip2, "\n")

# dot method
multip3 = arr1.dot(arr2)
print("multip3:", multip3, "\n")

# Bu esa haqiqiy kopaytirish emas!
multip4 = arr1 * arr2
print("multip4:", multip4)

multip1: [[12 14]
 [26 28]] 

multip2: [[12 14]
 [26 28]] 

multip3: [[12 14]
 [26 28]] 

multip4: [[ 2  0]
 [15 28]]


In [ ]:
# Test GitHub commit pushes