<a href="https://colab.research.google.com/github/SBekzod/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install pandas numpy

In [9]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("StudentsPerformance.csv")
df.tail()

gender race/ethnicity parental level of education         lunch  \
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86

# **MALUMOTLAR BILAN TANISHUV**

In [46]:
print(f"DataSet shape (row, column): {df.shape} \n")
print(f"Columns name: {df.columns.tolist()} \n")

print("✅ Top 5 data:\n", df.head(), "\n")

print("✅ Summary statistics:\n", df.describe(), "\n")

print("✅ Data types & null info:")
print(df.info())

DataSet shape (row, column): (1000, 8) 

Columns name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score'] 

✅ Top 5 data:
    gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4            

# **STATISTIK AMALIY AMALIYOT**

In [54]:
print("✅ Average score by columns:")
df[["math score", "reading score","writing score"]].mean()

✅ Average score by columns:


math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [53]:
print("✅ Max score by columns:")
df[["math score", "reading score","writing score"]].max()


✅ Max score by columns:


math score       100
reading score    100
writing score    100
dtype: int64

In [52]:
print("✅ Min score by columns:")
df[["math score", "reading score","writing score"]].min()

✅ Min score by columns:


math score        0
reading score    17
writing score    10
dtype: int64

In [55]:
print("✅ Correlation:")
df[["math score", "reading score","writing score"]].corr()

✅ Correlation:


math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [69]:
df["total score"] = df[["math score", "reading score","writing score"]].sum(axis=1) # row yani qator boyicha yig'amiz
df["average score"] = df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")

print("✅ AMALIY TAHLIL:")
df[["total score", "average score", "passed"]].head(10)

✅ AMALIY TAHLIL:


total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes
5          232      77.333333    Yes
6          275      91.666667    Yes
7          122      40.666667     No
8          195      65.000000    Yes
9          148      49.333333     No

# **GROUP BASED ANALYSIS**

In [79]:
print("✅ Guruh boyicha tahlil:")
test_group_analysis = df.groupby("test preparation course")[["math score", "reading score","writing score"]].mean()
print(test_group_analysis, "\n")
# Xulosa: test preparation course olganlar yuqori natija qayd etgan!

print("✅ Gender boyicha tahlil:")
gender_analysis = df.groupby("gender")[["math score", "reading score","writing score"]].mean()
print(gender_analysis, "\n")
# Xulosa: Erkaklar matematikada kuchli, ayollar esa reading va writingda kuchli ekan!

print("✅ Muvaffaqiyat boyicha tahlil:")
passed_analysis = df["passed"].value_counts(normalize=True) * 100
print(passed_analysis, "\n")


✅ Guruh boyicha tahlil:
                         math score  reading score  writing score
test preparation course                                          
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673 

✅ Gender boyicha tahlil:
        math score  reading score  writing score
gender                                          
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203 

✅ Muvaffaqiyat boyicha tahlil:
passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64 



In [95]:
# values state property
scores = df[["math score", "reading score","writing score"]].values

# Mean
print("✅ NumPy mean:\n", np.mean(scores, axis=0), "\n")

# Std
std_score = np.std(scores, axis=0)
print("✅ NumPy std:\n", std_score , "\n")

# Z-score (normalize)
z_score = (scores - np.mean(scores, axis=0)) / std_score
print("✅ z_score:\n", z_score[0:5]) # Average 0 | Positive + |Negative -


✅ NumPy mean:
 [66.089 69.169 68.054] 

✅ NumPy std:
 [15.15549666 14.59289002 15.18805728] 

✅ z_score:
 [[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]


In [104]:
top_scored = df[df["average score"] >= 90 ]
print("✅ Top scored:\n", top_scored["average score"].head() , "\n")
print("✅ Top scored counts:", len(top_scored) , "\n")

failed_students = df[df["passed"] == "No" ]
print("✅ Failed counts:", len(failed_students) , "\n")

✅ Top scored:
 2      92.666667
6      91.666667
104    91.333333
106    95.666667
114    99.666667
Name: average score, dtype: float64 

✅ Top scored counts: 52 

✅ Failed counts: 103 

